version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=inventorydb
      - MYSQL_ROOT_PASSWORD=adminpass
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: 'laguzs/iecomm-backend:1.2.1'
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
volumes:
  db:
